### ISSUE TITLE
pg_bulkload as standalone installation?

### ISSUE THREAD

**Issue by bilak** [ossc-db/pg_bulkload#12]
Hello,
I'm searching for "import tool" as standalone application to be able to perform import to remote database. As I've read in the documentation it's needed to have postgresql-server installed before. Is there any possibility to have standalone installation without need of postgresql-server? Or what are the steps if I only need pg_bulkload as a client to import data to remote db?

Many thanks

**Comment by bwtakacy** [comment]
Hello,

>As I've read in the documentation it's needed to have postgresql-server installed before.

Ah, the documentation is not correct. Sorry about confusing notation.

The RPM of pg_bulkload does not require postgresql-server, but requires the postgresql package which contains PostgreSQL client programs and libraries.

And pg_bukload can load data into remote database by INPUT=stdin like below

```
$ /usr/pgsql-9.5/bin/pg_bulkload -h 192.168.56.101 -d postgres -Upostgres -i stdin -O foo < data.csv
```

Does it fit your situation?

**Comment by bilak** [comment]
Ok I will try later this week. Can you also correct the documentation please?

Thanks

**Comment by bwtakacy** [comment]
> Can you also correct the documentation please?

Yeah, I will fix it.

One more point about remote load, you still need to install pg_bulkload in remote DB server and do 'CREATE EXTENSION pg_bulkload' in the target database.
If any trouble, please ask here :smile:

**Comment by bilak** [comment]
@bwtakacy is it possible to specify columns to which I want to load data from csv? I know there can be function for this, but is it possible to specify this in control file?

**Comment by bwtakacy** [comment]
No, there is not such a feature in control file.
