### ISSUE TITLE
Compile Error in Ubuntu LTS 22.04

### ISSUE THREAD

**Issue by phmauer** [ossc-db/pg_bulkload#126]
Hi there,

we will change our system from CentOS to Ubuntu LTS 22.04 and there we also want to use the pg_bulkload.

So i tried to follow your [instructions for the installation](http://ossc-db.github.io/pg_bulkload/pg_bulkload.html#install).
I've installed postgresql-server-dev-14, libpam0g-dev (that's the dev package i've found), libreadline-dev, libedit-dev & build-essential as mentioned.

![grafik](https://user-images.githubusercontent.com/105785217/169016690-82ac2d2e-8ea1-49a2-930b-e0a33395e261.png)
[make_error.txt](https://github.com/ossc-db/pg_bulkload/files/8715367/make_error.txt)

This is a local VM for testing purposes, freshly installed with Ubuntu LTS 22.04 and our needed PostgreSQL packages and a running pg-test instance.

But i've also tried same steps on an Ubuntu LTS 20.04 not too long ago and there it worked.

So i really don't know if some Libraries were deprecated or links are missing in the newer version.
Do you guys had some familiar problem in Ubuntu LTS 22.04?

Or does somebody already found a workaround / solution for this one?

Thanks in advance

kind regards
Philipp

**Comment by mikecaat** [comment]
Hi, try to install liblz4-dev because the error said lz4 libraries were missing.
ref: https://github.com/ossc-db/pg_bulkload/blob/master/.github/workflows/build.yml#L70

**Comment by phmauer** [comment]
Hello mikecaat,
thank you so much for the information.
After i've installed the missing liblz4-dev library everything can now be compiled!
