### ISSUE TITLE
Extension version pg_bulkload mistake

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ossc-db/pg_bulkload#141]
I compile the pg_bulkload using (version 3.1.20 https://github.com/ossc-db/pg_bulkload/releases/download/VERSION3_1_20/pg_bulkload-3.1.20.tar.gz):
USE_PGXS=1 make
USE_PGXS=1 make install

And when I install the extension:
create extension pg_bulkload;

Always show the version 1.0. Then I don't known if exists any fails or I missing any steps.

**Comment by mikecaat** [comment]
You mean the following results, don't you? It seems a little strange.

```
psql=# \dx
                                     List of installed extensions
    Name     | Version |   Schema   |                           Description
-------------+---------+------------+-----------------------------------------------------------------
 pg_bulkload | 1.0     | public     | pg_bulkload is a high speed data loading utility for PostgreSQL
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)
```

**Comment by mikecaat** [comment]
PR: #142

**Comment by cesarjorgemartinez** [comment]
I see the PR but, I have a doubt, you would be forces for each version to change manually this.

**Comment by zwyan0** [comment]
> I see the PR but, I have a doubt, you would be force for each version to change manually this.

Hi @cesarjorgemartinez ,thank you for your coment.
As you said, the previous code did have to manually modify the version each time, which is stupid.
So I made a modification.

**Comment by zwyan0** [comment]
> Great! Then LGTM

Thank you for your confirmation.
