### ISSUE TITLE
Building on Windows (x64)

### ISSUE THREAD

**Issue by 1803** [ossc-db/pg_bulkload#15]
I tried building v. 3.19 on Windows (10 x64) for PostgreSQL 9.5.2 (compiled by Visual C++ build 1800, 64-bit) in the following env:
1. MSVC 2013 (no Win SDK 7.1 installed, I change Build Toolset to v120)
2. MSVC 2010 (no Win SDK 7.1 installed, I change Build Toolset to v100)
3. MSYS2+mingw64

There is one common error I keep getting on all 3 of them:
```
binary.c:423:1: warning: no previous prototype for 'BinaryParam' [-Wmissing-prototypes]
 BinaryParam(Field **fields, int *nfield, char *value, bool preserve_blanks, bool length_only)
 ^
binary.c:423:1: error: 'BinaryParam' redeclared as different kind of symbol
In file included from D:/Programs/Dev/Env/msys64/mingw64/x86_64-w64-mingw32/include/rpc.h:104:0,
                 from D:/Programs/Dev/Env/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:88,
                 from D:/Programs/Dev/Env/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from D:/Programs/Dev/Env/msys64/mingw64/include/postgresql/server/pg_config_os.h:37,
                 from D:/Programs/Dev/Env/msys64/mingw64/include/postgresql/server/c.h:101,
                 from D:/Programs/Dev/Env/msys64/mingw64/include/postgresql/server/postgres.h:47,
                 from ../include/pg_bulkload.h:9,
                 from binary.c:11:
D:/Programs/Dev/Env/msys64/mingw64/x86_64-w64-mingw32/include/rpcasync.h:88:5: note: previous declaration of 'BinaryParam' was here
   } BinaryParam;
     ^
<builtin>: recipe for target 'binary.o' failed
mingw32-make[1]: *** [binary.o] Error 1
mingw32-make[1]: Leaving directory 'D:/Programs/Dev/Env/msys64/home/nick/pg_bulkload_319/lib'

```

When trying to build on MSVC I get that and a lot of syntax errors pointing to this line of logger.h code:

`__attribute__((format(PG_BULKLOAD_PRINTF_ATTRIBUTE, 2, 3)));`

I can attach any build log if it is required, but I think I'm missing something really simple.

**Comment by ooyamams** [comment]
Hi, Thank you for reporting.
But we have not maintained a Windows support for a long time.
We are discussing about it. Please wait.

Or we welcome to your pull request!

**Comment by 1803** [comment]
I figured `BinaryParam `is a reserved name for some other type in some of libraries, so I renamed it to `LocalBinaryParam `throughout the whole project.
Then I simply removed `__attribute__ `format strings because Visual Studio doesn't seem to know what that is, although mingw was ok with it.
After that I was able to build pg_bulkload_exe, but I still fail building the dll. Here's the errors I get:

```
1>parser_binary.obj : error LNK2001: unresolved external symbol LocalBinaryParam
1>parser_binary.obj : error LNK2001: unresolved external symbol BinaryDumpParams
1>pg_btree.obj : error LNK2001: unresolved external symbol wal_level
1>pg_bulkload.obj : error LNK2001: unresolved external symbol WriterDumpParams
1>pg_bulkload.obj : error LNK2001: unresolved external symbol WriterClose
1>pg_bulkload.obj : error LNK2001: unresolved external symbol WriterCreate
1>pg_bulkload.obj : error LNK2001: unresolved external symbol WriterInit
1>pg_bulkload.obj : error LNK2001: unresolved external symbol WriterParam
1>reader.obj : error LNK2001: unresolved external symbol pg_enc2name_tbl
1>writer_buffered.obj : error LNK2001: unresolved external symbol ON_DUPLICATE_NAMES
1>writer_buffered.obj : error LNK2001: unresolved external symbol get_relation_name
1>writer_parallel.obj : error LNK2001: unresolved external symbol setenv
1>...\pg_bulkload_319\msvc\/bin/x64/9.0/lib//pg_bulkload.dll : fatal error LNK1120: 12 unresolved externals
```

Some of these references seem to be related to libpq.lib or postgres.lib, but others (especially LocalBinaryParam) I have no idea why they can't be resolved.

**Comment by ooyamams** [comment]
Hi @1803 , Thank you for a more detail information.
But unfortunately we can't support Windows environments because we don't have Visual Studio and a developer of experience of Windows environments. So we couldn't help you.
If you could resolve this issue, please share the knowledge.
