### ISSUE TITLE
Unable to make build for Ubuntu 16.04 version

### ISSUE THREAD

**Issue by ultimatecoder** [ossc-db/pg_bulkload#17]
While generating build for this tool I am facing below traceback.

`$ make

make[1]: Entering directory <my-dir>/pg_bulkload/bin'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer pg_bulkload.o recovery.o pgut/pgut.o pgut/pgut-fe.o pgut/pgut-list.o -L/usr/lib/x86_64-linux-gnu -lpq -L/usr/lib/x86_64-linux-gnu -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib/x86_64-linux-gnu/mit-krb5  -Wl,--as-needed  -lpgcommon -lpgport -lselinux -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm -o pg_bulkload
/usr/bin/ld: cannot find -lselinux
/usr/bin/ld: cannot find -lpam
/usr/bin/ld: cannot find -ledit
collect2: error: ld returned 1 exit status
/usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/pgxs.mk:296: recipe for target 'pg_bulkload' failed
make[1]: *** [pg_bulkload] Error 1
make[1]: Leaving directory '<my-dir>/pg_bulkload/bin'
Makefile:27: recipe for target 'all' failed
make: *** [all] Error 2
`

Operating system: Ubuntu 16.04, 64bit

**Comment by bwtakacy** [comment]
Hmm.

There seems to be some libraries required which dependencies are inherited by PostgreSQL packaging in Ubuntu.
Try the below installation
```
sudo apt-get install libselinux-dev
sudo apt-get install libpam-dev
sudo apt-get install libedit-dev
```

Thanks.

**Comment by ultimatecoder** [comment]
That instruction helped. I believe the instructions should be added to the documentation of the project. I will try to create patch for the instructions. Closing this for now. Thanks!
