### ISSUE TITLE
How to install pg_bulkload to Ubuntu 16.04

### ISSUE THREAD

**Issue by ultimatecoder** [ossc-db/pg_bulkload#18]
Is there any package available for installing pg_backload to Ubuntu 16.04? From the documentation I only found RHL package. The option I found is only generating build from source. Please replay if anyone knows better way than source installation. Thanks!

**Comment by bwtakacy** [comment]
Currently it is the only way to build from source in Ubuntu.

**Comment by ooyamams** [comment]
Hi!
It seems to me that you should ask pgapt (PostgreSQL Debian and Ubuntu Repository Team).
https://redmine.postgresql.org/projects/pgapt/issues

**Comment by brainbuz** [comment]
Its not hard to install but you need to get the dependencies and sometimes symlink things that aren't where make expects them, here's my latest install on Ubuntu Xenial as a shell script.
#!/bin/bash

PG_TARGET=$1
apt-get install "postgresql-server-dev-$PG_TARGET"
apt-get install "build-essential" "git" "libpam0g-dev"
apt-get install "libedit-dev" "libselinux1-dev" "openssl" "libssl-dev"

ln -s "/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2" "/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so"

git clone "https://github.com/ossc-db/pg_bulkload.git" /opt/pg_bulkload

cd /opt/pg_bulkload
make clean
make
make install

ln -s /opt/pg_bulkload/bin/pg_bulkload /usr/local/sbin/pg_bulkload
sudo -u postgres psql postgres < /opt/pg_bulkload/lib/pg_bulkload.sql

**Comment by egalot** [comment]
Hi @brainbuz, I get the following errors during the make:

/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport

I have peformed the installation of the pg development packages using:  sudo apt-get install postgresql-server-dev-10

Any additional tips.

**Comment by brainbuz** [comment]
egalot I haven't needed to build with either pg 10 or with bionic yet .
/usr/bin/ld is gnu linker so you are either missing a dependency or need to help the linker find it with a symlink. I would guess that since you installed the dev package you need to figure out the missing symlink(s).

**Comment by egalot** [comment]
Hey, thanks for writing. I was able to make it compile my modifying and
then running manually the gcc line that was failing. I added the following
option:

-L/usr/lib/postgresql/10/lib

and removed the option:

-lpam

and the compilation succeeded. No idea why these lines were missing from
the original gcc line generated by Makefile and I nor I don't know how to
modify the Makefile so that it adds these options. Now I am about the test
the resulting executable to see if it works. Thanks for your help.

Emil

**Comment by egalot** [comment]
Well I was too quick to call victory on this one, although the application compiled, additional steps did not execute properly and thus the application fails to properly register itself as a postgres module. I am still hoping to find a solution.
