### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by CatsMum** [ossc-db/pg_bulkload#19]
This doesn't seem to handle Unicode, formatted as UTF-8 for input data.

**Comment by ooyamams** [comment]
Do you use **ENCODING** in Control Files?
http://ossc-db.github.io/pg_bulkload/pg_bulkload.html#controlfile

Please show us Steps to reproduce.

**Comment by CatsMum** [comment]
The data is UTF-8 encoded. The table also uses UTF-8. As I understand the page you've directed me, there is no need for an ENCODING clause. However, I've solved my problem by not using pg_bulkload.
