### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by brainbuz** [ossc-db/pg_bulkload#2]
I was just installing pg_bulkload and would like to suggest adding the dependencies for popular distributions in the install section.
To install on ubuntu I needed build-essential, git, postgresql-server-dev-x.x, libpam0g-dev, libedit-dev.

**Comment by bwtakacy** [comment]
Thanks for suggesting.

That's sounds nice for users who try to build pg_bulkload from source code.
I will do this.
