### ISSUE TITLE
Out of memory with a function as Input

### ISSUE THREAD

**Issue by collini** [ossc-db/pg_bulkload#22]
Hello, since some weeks ago (maybe data log increased), we notice sometime an "out of memory" error in pg_bulkload (3.1.9 version) when we use, as input, a postgresql function
pg_bulkload 3.1.9 on 2016-10-04 09:18:23.033388+02

INPUT = pg_bulkload_function_name()
WRITER = DIRECT
..........
out of memory

When loading other types of data (until 10 millions of row with a CSV file), everything works.
It seems a memory leak when using this function...
Someone has experienced this problem?

Thank you, best regards!
Francesco

**Comment by amitlan** [comment]
I don't seem to be able to reproduce this error.  At least I didn't see any memory being leaked while looking at the loading process nor did I see "out of memory" error.

Can you provide some more details, like, what is the exact error message you see and where do you find the error message (in the server log or on the command line where pg_bulkload program is invoked)? Can you provide more details about the function you are using?

**Comment by collini** [comment]
Hi Amit and thank you for your kind interest.
That error appeared in pg_bulkload log but it referred to an "Sql input function" that, having too much results, exited with postgresql "out of memory" error.

I was able to debug the problem only now, and it is not related to pg_bulkload but to the query/Postgresql database system.

Thank yo for your interest end excuse me for the disturb! :)

Francesco, from italy
________________________________
Da: Amit Langote [mailto:notifications@github.com]
Inviato: mercoledì 5 ottobre 2016 09:56
A: ossc-db/pg_bulkload
Cc: Collini, ColliniConsulting.it; Author
Oggetto: Re: [ossc-db/pg_bulkload] Out of memory with a function as Input (#22)


I don't seem to be able to reproduce this error. At least I didn't see any memory being leaked while looking at the loading process nor did I see "out of memory" error.

Can you provide some more details, like, what is the exact error message you see and where do you find the error message (in the server log or on the command line where pg_bulkload program is invoked)? Can you provide more details about the function you are using?

-
