### ISSUE TITLE
Should default for CHECK_CONSTRAINTS be ON?

### ISSUE THREAD

**Issue by amitlan** [ossc-db/pg_bulkload#31]
I just noticed that if a target table has check constraints, they are not checked by pg_bulkload by default (although NOT NULL constraints of individual columns are).  Should that be reverse?

**Comment by bwtakacy** [comment]
I do not know why exactly is but I think it is just for performance.

**Comment by amitlan** [comment]
Ah, okay.  Given that pg_bulkload is all about fast loading, that may be OK.
