### ISSUE TITLE
Loading data into PG 10 partitions

### ISSUE THREAD

**Issue by amitlan** [ossc-db/pg_bulkload#32]
PG 10 has partitioned tables.  We cannot target the partitioned tables directly because they do not have their own storage.  But we can load data directly into partitions, assuming the data being loaded satisfies the partition constraint.  PostgreSQL will apply the partition constraint if data is *directly* inserted into a partition.

I think `pg_bulkload` should do the same.  `CheckerInit()` should also initialize the partition constraint, in addition to traditional constraints.

**Comment by bwtakacy** [comment]
Nice feature :)

Let's discuss about the specification of this.
Maybe it enables a input file load into a single partition, isn't it?
Is it useful to detect the target partition automatically from the input file or control file?

**Comment by amitlan** [comment]
Handling loading into partitioned tables would be quite some work as it requires some initial setup for tuple routing.  For each input tuple, an executor function called `ExecFindPartition()` is called to determine the target partition whose `RelationData` pointer is passed to `heap_insert()`, along with the `HeapTuple` corresponding to the tuple.  In other words, the answer to your last question is perhaps no -  routing individual tuples to target partitions needs to be handled explicitly.

On the other hand, loading into a partition works just like any regular table.  If the file contains a record that doen't satisfy the partition constraint, it has to be rejected.  pg_bulkload's writers need to learn how to do that.  We cannot skip checking the partition constraint unlike regular user-defined `CHECK` constraints, which is a pg_bulkload feature.  Since checking partition constraint is embedded inside `ExecConstraints()`, that means we cannot skip calling it, which in turn means we will end up checking the regular `CHECK` constraints even if don't want.  Perhaps the fact that partition constraint checking is embedded inside `ExecConstraints()`  is undesirable, so I need to talk to pgsql-hackers about that - we may need publicly accessible `ExecPartitionCheck()`.

Anyway, it might be too early to consider partitioned tables at this point.  So closing this issue.

**Comment by bwtakacy** [comment]
Hmm.

Many hardles.
But, it may be a big feature for new major version up.
I hope we will back to this again:)
