### ISSUE TITLE
Postgres-Pg_bulkload Filter syntax for C program

### ISSUE THREAD

**Issue by rajmhnr** [ossc-db/pg_bulkload#33]
In Pg_bulkload, following syntax is used for SQL FILTER. 

    CREATE FUNCTION sample_filter (integer, text, text, real DEFAULT 0.05) RETURNS record
        AS $$ SELECT $ 1 * $ 4, upper ($ 3) $$
        LANGUAGE SQL;

I can't find any sample syntax for C programming.As per documentation, C filter is much faster than SQL filter. 

Anybody have used C programming Filter? Kindly provide some sample syntax?

Thanks

**Comment by amitlan** [comment]
Have you read [this](https://www.postgresql.org/docs/current/static/xfunc-c.html) chapter in PostgreSQL documentation about writing C-language functions?

To summarize:

* Simply write your filter function named `sample_filter()` in a C source code file, say, `bulkload_filter.c`
* Compile as a shared library (in our case, `bulkload_filter.so`)

```
gcc -I $PG_INSTALL_DIR/include/postgresql/server \
      -fPIC -shared -o bulkload_filter.so bulkload_filter.c
```

* Put the resulting shared library file in appropriate location for the PostgreSQL server to locate, say, into directory called `DIRECTORY` (absolute path fine)
* Then register it into the server by defining a SQL-callable function in the database as follows:

```
CREATE FUNCTION sample_filter(integer, text, text, real DEFAULT 0.05) RETURNS integer
     AS 'DIRECTORY/bulkload_filter', 'sample_filter'
     LANGUAGE C STRICT;
```

**Comment by rajmhnr** [comment]
Thanks. It was greatly helpful.

I was trying to accomplish the below task. Reading the data from file.Here is the sample data.File has no header.

```
Sample Data:
ABC|20170101|DEF ||GHIJ|KLM
```

```
Target Table Definition:
COLA numeric(5,0)
COLB date
COLC text
COLD text
COLE text
```
```
First column-->COLA
Second column-->COLB
Third column-->COLD
Fourth column-->COLC
Fifth column-->Some default value(column is not present in source) 
```
```
Transformation:
-->First column-->COLA. It is numeric in target table. If any alpha-characters were present, default this column with '0'. Otherwise, source value should be moved to table.
-->Second column-->COLB. TO_DATE function from text format. File will have date format as YYYYMMDD. It should be converted to date.
-->Third column-->COLD.Need to Trim both leading and trailing spaces.
-->Fourth column-->COLC. If it NULL, some value should be defaulted.
-->Only few columns from source file should be loaded. In this case, only first four columns should be loaded.
-->Different ordering in source files & target columns.In this case,
        Third column-->COLD
        Fourth column-->COLC
-->COLE should be loaded with default value. This column is not present in source file.
```
These transformations, can be handled with query after loading all the data as varchar and nullable. But we need to handle this before loading as like we do in Oracle.

Do you think, these functionalities can be accomplished using C programming? I'm new to C. Some standard syntax for writing these functionalities would be greatly helpful.

Thanks

**Comment by amitlan** [comment]
It's definitely possible to do the transformations using a C FILTER function.  You would need to write it using PostgreSQL-style C code to interface with the rest of the code.  You will also be able to use a library of functions already defined in PostgreSQL to do things like convert using `TO_DATE`, trim white space,  etc.

As mentioned in my first comment, PostgreSQL documentation has [rich documentation]() about writing functions in C.  There is a sentence there:

> Hence, the standard internal function library is a rich source of coding examples for user-defined C functions.

That means you can look at how library functions are implemented and try to write code like that, except you will implement the FILTER logic.  You will learn things like how to receive individual fields of an input row, how to manipulate it using PostgreSQL library functions or your own code, and finally return the output row back, etc.  Basically, the input/output is accomplished with certain macros like `PG_GETARG_TEXT_PP(<argnum>)`, `PG_RETURN_TEXT_P(<return-value>)`, then there are macros/functions to manipulate values of variable-length data like text, varchar, etc. (values of some data types like integer are manipulated using native C type values).

It certainly has a learning curve associated with it, but you will feel rewarded once you are able to achieve what you want to with it.

**Comment by amitlan** [comment]
Closing if no more questions about this.

To summarize, learn writing PostgreSQL C functions by referencing its documentation.  It's not feasible to explain that in pg_bulkload documentation.
