### ISSUE TITLE
Regarding the gh-pages branch, doc/index.html and pg_bulkload.html

### ISSUE THREAD

**Issue by amitlan** [ossc-db/pg_bulkload#37]
We recently could get rid of the `gh-pages` branch in the pg_rman repository.  The requirement for the new GitHub pages feature was to have a `doc/index.html` in the master branch.  We do have for one in the pg_bulkload repository too, but we don't update it when we make releases.  Rather, we update `pg_bulkload.html` which is linked from `index.html`.  I just noticed that we forgot to mention information about releases 3.1.10 onward, so pushed a fix to the copy of `pg_bulkload.html` in the `master` and `VERSION3_1_STABLE` branches, which didn't result in updating what I can read [here](http://ossc-db.github.io/pg_bulkload/pg_bulkload.html).  Pushing the same fix in the `gh-pages` branch worked.

I'm wondering which files are picked up by `ossc-db.github.io/pg_bulkload/`?  To be specific, which branch of the repository.  I mean, since we have `doc/index.html` in the `master` branch, and if that's what is being used, then why isn't `pg_bulkload.html` in the same branch used to link to?

**Comment by bwtakacy** [comment]
The HTML files in `gh-pages` were branched from `VERSION3_1_STABLE`.

The master branch was for the next major version 3.2 but the development was stopped from long ago.
We keep maintaining the version 3.1.x in `VERSION3_1_STABLE` and so the documentation to be published is the files in this branch. Not the files in `master` branch.

The HTML files in `gh-pages` has its origin in `VERSION3_1_STABLE`.

I agree to use the new GitHub pages feature to prevent the lack of update such as the recent one.
One idea is swap the `master` branch and `VERSION3_1_STABLE` branch.
I mean that take `master` branch to `VERSION3_2_DEV` and move `VERSION3_1_STABLE` to `master`.

How do you think?

**Comment by amitlan** [comment]
I think that's a good idea.

**Comment by bwtakacy** [comment]
Thanks.

I have found the discussion about branch swapping.

http://stackoverflow.com/questions/17200035/swap-a-master-and-a-feature-branch

Though this is a kind of destructive change, we should be careful to actually do.

**Comment by bwtakacy** [comment]
@amitlan @atorik 
Do you have any request schedule to do the branch swapping?

**Comment by amitlan** [comment]
Yeah, no problem I think.  Thanks!

**Comment by bwtakacy** [comment]
OK!
I will do it in this weekend holidays. 👍

**Comment by bwtakacy** [comment]
I have done the branches swapping and change to use the new GitHub Pages features.
Now the `gh-pages` branche is no longer necessary, but I keep it for a while for other member's confirmation.

By the way, I have found the recent PostgreSQL updates breaks pg_bulkload build.
https://github.com/postgres/postgres/commit/f1b4c771ea74f42447dccaed42ffcdcccf3aa694

@amitlan Seem that you are the best one to solve this :)
We need to add one more argument of `ExecConstraints` about TupleTableSlot pointer related to partitioned tables.

**Comment by amitlan** [comment]
Thanks a lot for doing that!

About the `ExecConstraints()` case, I think it might be better to wait a little, because I recently proposed (in the pgsql-hackers ML) to revert that interface change.

**Comment by bwtakacy** [comment]
OK.

Keep it until PostgreSQL side update:)

**Comment by amitlan** [comment]
I will close this issue now, thanks a lot!
