### ISSUE TITLE
Passing arguments more than 100

### ISSUE THREAD

**Issue by rajmhnr** [ossc-db/pg_bulkload#39]
I have more than 100 columns from input file. So i used more than 100 arguments in Postgres function. But Postgres doesn't support 100 arguments in function.

Then i tried using composite type with simple example;

Create Type;

CREATE TYPE test_123 AS (
    name            text,
    supplier_id     integer,
    price           numeric
); 

Then called Type inside the Postgres function like below;

CREATE OR REPLACE FUNCTION test123(test_123)
  RETURNS record AS
$BODY$ SELECT $1.name, $1.price $BODY$
  LANGUAGE sql VOLATILE
  COST 100;

Created Table:

create table test123 
(
name text,
price numeric(5,0)
)

Input file;
raja|0|100

But the table was not loaded; Got the below error;

**Parse error Record 1: Input Record 1: Rejected - column 3. extra data after last expected column
Maximum parse error count exceeded - 1 error(s) found in input file**

If input file has data something like this, it works.

(raja,0,100)

Did the conversion using UNIX SED command from raja|0|100 to (raja,0,100). It's taking 5 minutes for 16 million data. But it's not ideal solution.

Can you please help me, how this case can be handled? Our data was supposed to be delimited without braces. Definitely, someone would have faced this issue before.

Thanks

**Comment by amitlan** [comment]
100 argument not being supported is a PostgreSQL server limitation.  pg_bulkload developers cannot do anything about it, unfortunately.  But it seems you understand that.

You would need to find a way that doesn't require to use a function.  Why do you need to use the function anyway?

**Comment by rajmhnr** [comment]
I'm validating and transforming the data using SQL filter.For this Postgres function is required.Having more than 100 fields in source file.Doing transformation for nearly 20-30 fields.

Any other way to do it?

**Comment by amitlan** [comment]
Well, you already said you hit a limitation of PostgreSQL functions (namely it cannot handle more than 100 arguments).  So, you will have to perform any transformations on the input file *before* you use pg_bulkload, perhaps using some UNIX utilities.

The bottom line here is, to use pg_bulkload's FILTER capability, you have to rely on PostgreSQL functions.

**Comment by bwtakacy** [comment]
> Did the conversion using UNIX SED command from raja|0|100 to (raja,0,100). It's taking 5 minutes for 16 million data. But it's not ideal solution.

I think it is better to use some distributed processing, like hadoop or spark,  to transform data for input format...

**Comment by rajmhnr** [comment]
Thank you.Going ahead with UNIX approach.

**Comment by amitlan** [comment]
Alright, OK to close the issue?

**Comment by rajmhnr** [comment]
Sure. Thanks
