### ISSUE TITLE
9.3 Installation Error

### ISSUE THREAD

**Issue by diplonics** [ossc-db/pg_bulkload#4]
I'm having trouble installing pg_bulkload.
The server originally hosted postgresql 9.0 with pg_bulkload 3.0 working fine but I have since removed V9.0 and upgraded to V9.3 but I can't get pg_bulkload 3.1 to re-install.
Can you see anything obvious as to why it won't install for me from the log below.
Something to do with -ledit so I'm missing a package of some sort but can't work out what.

Any help much appreciated.

Paul

paul@re-srv-2ek:~/pg_bulkload_3.1$ make
make[1]: Entering directory `/home/paul/pg_bulkload_3.1/bin'
gcc -g -O2 -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/9.3/server -I/usr/include/postgresql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.5  -c -o pg_bulkload.o pg_bulkload.c
gcc -g -O2 -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/9.3/server -I/usr/include/postgresql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.5  -c -o recovery.o recovery.c
gcc -g -O2 -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/9.3/server -I/usr/include/postgresql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.5  -c -o pgut/pgut.o pgut/pgut.c
gcc -g -O2 -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/9.3/server -I/usr/include/postgresql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.5  -c -o pgut/pgut-fe.o pgut/pgut-fe.c
gcc -g -O2 -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/9.3/server -I/usr/include/postgresql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.5  -c -o pgut/pgut-list.o pgut/pgut-list.c
gcc -g -O2 -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g pg_bulkload.o recovery.o pgut/pgut.o pgut/pgut-fe.o pgut/pgut-list.o -L/usr/lib -lpq -L/usr/lib -Wl,-Bsymbolic-functions -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib//mit-krb5 -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib//mit-krb5  -Wl,--as-needed  -lpgport -lpgcommon -lpam -lssl -lcrypto -lkrb5 -lcom_err -lgssapi_krb5 -lz -ledit -lcrypt -ldl -lm -o pg_bulkload
/usr/bin/ld: cannot find -ledit
collect2: ld returned 1 exit status
make[1]: *** [pg_bulkload] Error 1
make[1]: Leaving directory `/home/paul/pg_bulkload_3.1/bin'
make: *** [all] Error 2
paul@re-srv-2ek:~/pg_bulkload_3.1$

**Comment by bwtakacy** [comment]
I guess this error happens because of lack of libedit-dev package.
This library is not required by pg_bulkload but by PostgreSQL.
Though the build script of pg_bulkload is depends on that of PostgreSQL, this library requirement is inherited. 

Could you run `apt-get install llibedit-dev` and try again?

**Comment by diplonics** [comment]
That worked perfectly thank you very much, all up and running now.
Just to clarify a typo its libedit-dev that worked for me, not llibedit-dev.

Thanks again,

Paul

**Comment by bwtakacy** [comment]
Oh, sorry for my confusing typo.

I'm happy to hear your succeed:)

Regards,
