### ISSUE TITLE
Pg_bulkload loading

### ISSUE THREAD

**Issue by rajmhnr** [ossc-db/pg_bulkload#41]
Hi,

I have few questions to ask.Can you help me with that?

-->Pg_bulkload is more like Sql loader in Oracle right? What if the table has indexes. Will it be rebuild after loading data as like oracle? Not sure, how this process works.
-->In pg_bulkloads, records will be inserted not updated. right?
Came across, few records got replaced. Is it because of ON_DUPLICATE_KEEP = NEW. Will that be be updated, or record will be removed and re-inserted. Kindly clarify that.

Thanks

**Comment by bwtakacy** [comment]
Hi,

>-->Pg_bulkload is more like Sql loader in Oracle right? What if the table has indexes. Will it be rebuild after loading data as like oracle? Not sure, how this process works.

Yes, the indexes are rebuilt after loading data, not to updating indexes in insertition.

> -->In pg_bulkloads, records will be inserted not updated. right?
Came across, few records got replaced. Is it because of ON_DUPLICATE_KEEP = NEW. Will that be be updated, or record will be removed and re-inserted. Kindly clarify that.

Yes, load records are inserted, not updated.
In default configuration,ON_DUPLICATE_KEEP does not work because DUPLICATE_ERRORS is non zero.
Could you tell us the situation more detail?

**Comment by rajmhnr** [comment]
Thanks.

This is my case, where records got replaced and i have a settings as 

DUPLICATE_ERRORS = 0
ON_DUPLICATE_KEEP = NEW

This is normal.right? If any record was already present, that particular record will be replaced by a record from source.

I have one more question. Will pg_bulkload disable the trigger before loading? I don't want to disable the trigger.

**Comment by bwtakacy** [comment]
> This is normal.right? If any record was already present, that particular record will be replaced by a record from source.

Yes, that is the default configuration.
I think that pg_bulkload will abort if there is duplicated records in this configuration.

> I have one more question. Will pg_bulkload disable the trigger before loading? I don't want to disable the trigger.

Yes, pg_bulkload does not call triggers.

**Comment by rajmhnr** [comment]
Thanks.

We created partitioned table based on month or day. 

Based on the process date in source file, trigger will look whether the partitioned was already present, if not, will create a partition and load the data.That's essential from our side.

Any other workaround for this using pg_bulkload.

**Comment by bwtakacy** [comment]
Because pg_bulkload does not use triggers, you should prepare data files for each partition tables and load each files into each partition tables by pg_bulkload.

**Comment by rajmhnr** [comment]
Thanks
