### ISSUE TITLE
Load the data to another server using pg_bulkload

### ISSUE THREAD

**Issue by rajmhnr** [ossc-db/pg_bulkload#42]
We have following scenario

Server-1(DB)
Server-2(ETL)-Etl jobs will write the data to a file; These files will be loaded to table which was present in server1 using pg_bulkload.

Planning to install only pg_client .Will it work without postgres server?

Thanks

**Comment by bwtakacy** [comment]
Pg_bulkload consists of client command and server function. 
You need to install pg_bulkload both in server-1 and server-2.

Register the pg_bulkload's server function by doing `CREATE EXTENSION pg_bulkload` in server-1, and call the pg_bulkload's client command in server-2 like 
```
$ pg_bulkload load.ctl < input_data.csv
```
with `INPUT=stdin` which read data from local file in server-2 via standard input.

**Comment by rajmhnr** [comment]
Thanks.

In Server-2, Postgres server installation is not required. right? 

Right now, we are calling pg_bulkload like below(DB & ETL were in same server). Input file name was specified inside the control file.

/usr/pgsql-9.5/bin/pg_bulkload load.ctl -d database -U username -w 1

It should be called in server 2 something like below. 

pg_bulkload load.ctl < input file

Will the performance be affected because of using INPUT=stdin?

**Comment by bwtakacy** [comment]
> In Server-2, Postgres server installation is not required. right?

Yeah. The PostgreSQL client package is only required in server-2.

> Will the performance be affected because of using INPUT=stdin?

Maybe.
But, i think `WRITER=PARALLEL` can be prevent the performance down at some degree.
In `WRITER=PARALLEL` configuration pg_bulkload use two processes, for reading data from input and for writing data to PostgreSQL. This makes pg_bulkload not to wait the remote data reading.

**Comment by rajmhnr** [comment]
Thanks. If both servers were present in same network, I hope, there will not be issue in performance.

Syntax to call in Server 2:
pg_bulkload load.ctl < input file -d database -U username -w 1
Is that right? Please correct if i'm wrong.

I have two more question. 
-->Even if I set WRITER=PARALLEL, In background, it was treated as following in log
WRITER=DIRECT and MULTI_PROCESS=YES.
So, i have kept the configuration directly as WRITER=DIRECT and MULTI_PROCESS=YES. Correct if i'm wrong.
-->What is the difference between WRITER & LOADER. Both were same, right?

Thanks again for your valuable inputs.

**Comment by bwtakacy** [comment]
> Syntax to call in Server 2:
pg_bulkload load.ctl < input file -d database -U username -w 1
Is that right? Please correct if i'm wrong.

I did not confirm but, the stdin argument should be the last;
```
$ pg_bulkload -d database -U username -w 1 load.ctl < inputfile
```

>-->Even if I set WRITER=PARALLEL, In background, it was treated as following in log
WRITER=DIRECT and MULTI_PROCESS=YES.
So, i have kept the configuration directly as WRITER=DIRECT and MULTI_PROCESS=YES. Correct if i'm wrong.

It's OK.
The `WRITER=PARRALEL` is a kind of syntax sugar and it equals to `WRITER=DIRECT` and `MULTI_PROCESS=YES`.

>-->What is the difference between WRITER & LOADER. Both were same, right?

Yes, they are same.

**Comment by rajmhnr** [comment]
Thanks. Tried following. 

**Server 1:(DB server)**
Installed pg_bulkload in server 1. It looked for following dependencies, since postgres server was already installed, we don't have any issue.
Dependencies:
libpq.so.5()(64bit) is needed by pg_bulkload95-3.1.10-1.rhel6.x86_64
postgresql95-server is needed by pg_bulkload95-3.1.10-1.rhel6.x86_64 

# rpm -ivh pg_bulkload95-3.1.10-1.rhel6.x86_64.rpm

**Server 2:(ETL server)**
Here we need to install pg_bulkload client alone without postgres server. ETL will write all the files in this  server. Without moving the file to Server 1, all loading should happen from server 2. 

Tried to install pg_bulkload with following package but it requires postgres server and library dependency.

rpm -ivh pg_bulkload95-3.1.10-1.rhel6.x86_64.rpm

Any other package is available without postgres server dependency? Or any other work around is available? Kindly help me.

Thanks Again.

**Comment by bwtakacy** [comment]
> rpm -ivh pg_bulkload95-3.1.10-1.rhel6.x86_64.rpm

Ah, you are using the rpm package released by PDGD.
Our original packages do not require PostgreSQL server package, but there is no 3.1.10 package for rhel6 x86_64.

@atorik Could you create a rpm package for @rajmhnr ?

**Comment by bwtakacy** [comment]
@rajmhnr 

I have created a rpm which does not require PostgreSQL server package.
Please try the attached one in Server 2.

[pg_bulkload-3.1.10-1.el6.x86_64.rpm.zip](https://github.com/ossc-db/pg_bulkload/files/760997/pg_bulkload-3.1.10-1.el6.x86_64.rpm.zip)

**Comment by MichaelDBA** [comment]
is there an apt package for this on debian/ubunto distros?

**Comment by bwtakacy** [comment]
@MichaelDBA 
No, we do not create apt packages now.
If you want, I will try to create :)
Please create a new ticket about it and give a request.

**Comment by rajmhnr** [comment]
Thanks bwtakacy. It will be greatly helpful.
