### ISSUE TITLE
Load CSV file with HEADER

### ISSUE THREAD

**Issue by alfredorico** [ossc-db/pg_bulkload#46]
Hi,

I have a CSV file with HEADER. There is no reference within documentation about how to indicate if the CSV file do contains or doesn't contains a HEADER. It seems like a CSV file can't contain a HEADER.

Please, how could I take on that..

**Comment by atorik** [comment]
I think the number of HEADER row is one, so how about adding 'SKIP = 1' to your ctl file?

**Comment by alfredorico** [comment]
Wow! Excellent! That's what I was needing. Thanks!..
