### ISSUE TITLE
pg_bulkload 3.1.13 supports pg9.5?

### ISSUE THREAD

**Issue by LoveTommy** [ossc-db/pg_bulkload#50]
what's new features going to add pg_bulkload?

**Comment by atorik** [comment]
pg_bulkload 3.1.13 supports 9.5.
Please refer to [release notes](https://github.com/ossc-db/pg_bulkload/releases).

We are going to add features which are necessary to work on newer PostgreSQL versions.

**Comment by LoveTommy** [comment]
Can pg_bulkload run on the windows ?

**Comment by atorik** [comment]
Unfortunately pg_bulkload does not support Windows environments.

**Comment by LoveTommy** [comment]
I recently compare the performance between copy and pg_bulkload, when "writer=buffered"  pg_bulkload slow than the copy. I read the code ,but I don't know why.

**Comment by atorik** [comment]
I have no experience of measuring pg_bulkload performance,   but when "writer" is "buffered", pg_bulkload writes WALs, so i imagine this mode is not so fast.

There is a [performance test results](http://pgbulkload.projects.pgfoundry.org/index.html) comparing pg_bulkload in direct/parallel mode and COPY, and pg_bulkload was faster.

**Comment by atorik** [comment]
There was a test result comparing various pg_bulkload modes.

@amitlan
Thanks for sharing!


>  ---loading  277MB csv file ---
>  mode				: loading times (in seconds) 
>  COPY (with indexes)	:	30
>  COPY (without indexes)	:	20
>  BUFFERED		        :	25
>  PARALLEL_BUFFERED	:	15
>  DIRECT			:	14
>  PARALLEL		:	12

BUFFERED writer combined with MULTI_PROCESS=YES (parallel) gained some performance benefits compared to simple BUFFERED writer, so adding  MULTI_PROCESS=YES will improve the result.

**Comment by LoveTommy** [comment]
./pg_bulkload -i '/Users/wanggang/test.sql' -O test -l '/Users/wanggang/pg9.5/test.log' -o "WRITER=BUFFERED" -o "MULTI_PROCESS=YES"

NOTICE: BULK LOAD START
ERROR: query failed: ERROR: shmget(id=1850950055) failed: invalid argument
DETAIL:query was :SELECT * FROM pg_bulkload($1)

PARALLEL_BUFFERED mode I input is right? Or there may be other things ? @atorik

**Comment by amitlan** [comment]
@LoveTommy 

That does not seem like a pg_bulkload issue.  Have you checked that the kernel's System V shared memory (shmmax, shmall, etc.) parameters are sufficient?

Also, pg_bulkload does not support a mode named `PARALLEL_BUFFERED`, so you should not try to use in the control file or parameters specified using command line.

**Comment by LoveTommy** [comment]
How make pg_bulkload run on windows? I try some ways, but compile cant't pass. @atorik @amitlan

**Comment by amitlan** [comment]
@LoveTommy Hmm, I don't have much experience with building pg_bulkload (or any PostgreSQL-related software for that matter) on the Windows platform.  Also, I am not sure if anyone has updated the build-related files under `msvc/` for a long time.  If you can do that and show any specific problem you are having, I might be able to help.  If it is some Windows build environment issue, I will not be able to help immediately.

**Comment by LoveTommy** [comment]
@amitlan I am not sure if someone has built pg_bulkload successfully on windows , atorik said pg_bulkload cann't run on windows.

**Comment by amitlan** [comment]
Hmm yes.  We don't support building pg_bulkload on Windows, as currently none of us pg_bulkload developers have the experience of Windows build environment.

Closing this.  If you'd like to ask more or maybe provide a patch to fix the Windows build issues, feel free to create a new issue or send a PR.
