### ISSUE TITLE
postgresql script

### ISSUE THREAD

**Issue by LoveTommy** [ossc-db/pg_bulkload#53]
In direct mode, if i don't use postgresql script,  what result will be ? @amitlan

**Comment by atorik** [comment]
In direct mode, it is necessary to use postgresql script and invoke "pg_bulkload -r" as mention in manual.

http://pgbulkload.projects.pgfoundry.org/pg_bulkload.html

> When pg_bulkload is crashed and some .loadstatus files are remained in $PGDATA/pg_bulkload, database must be recovered by pg_bulkload own recovery with "pg_bulkoad -r" command before you invoke pg_ctl start.
