### ISSUE TITLE
How to interrup pg_bulkload in a safe way?

### ISSUE THREAD

**Issue by alfredorico** [ossc-db/pg_bulkload#54]
Hi to everybody,

I must ask for apologize due to this is not an issue. I just want to consult expert people in the best place.

I'm developing a ruby gem that use pg_bulkload to load a very huge CSV file, but it's possible that the proccess could be interrupted. How could I stop a running pg_bulkload in a safe way? I mean, the CSV file must be loaded normally just until the moment of interruption. Do I must sent a especial kill code ?(something else to kill -9)
Please any suggest are welcome.

Thanks in advance.

**Comment by atorik** [comment]
pg_bulkload does not have a feature to pause and resume data load.

Your problem seems to come from csv data size, so how about splitting data load?
You can split data load by making multiple pg_bulkload control files and indicating appropriate SKIP and LIMIT.

An Example for loading 1000 rows for each bulkload:

> control file1:
>   SKIP = 0
>   LIMIT = 1000
> 
> control file2:
>   SKIP = 1000
>   LIMIT = 1000
> 
> control file3:
>   SKIP = 2000
>   LIMIT = 1000

**Comment by alfredorico** [comment]
Hi @atorik, thank you very much for your answer.
Actually, I don't want to pause and then resume. I just want to stop and finish the current load without damage.
I find a way but I'dont know if it is really safe. It's seems to be safe.
When a pg_bulkload start, if I press Ctrl C (send SIGINT signal), during any moment of execution, the proccess is stopped and data isn't lodaded. I think it's really.
Thence what I did was to get pid of the pg_bulkload proccess (started from ruby) and send it a SIGINT signal and that works (from Ruby) and it works. 
But, is it that safe?..
The target table doesn't seem to be locked or broken.

Any ideas?.

Thanks a lot!.

**Comment by amitlan** [comment]
@alfredorico Yes, it's safe.

When you run pg_bulkload using a terminal, there are two processes running:

1. One running in terminal waiting for the user input
2. A PostgreSQL backend process doing the actual loading of data

Process handling the user input (the terminal one) will catch the Ctrl-C interrupt and send a cancel request to the backend.  Upon receiving the cancel request, the loading process will abort the transaction in which the data is being loaded, which will restore the table to the state it was before the loading transaction began.

**Comment by amitlan** [comment]
Closing this as my last answer might have somewhat cleared up doubts about the safety of interrupting.
