### ISSUE TITLE
Set permissions for errors and log files generated

### ISSUE THREAD

**Issue by alfredorico** [ossc-db/pg_bulkload#55]
Hi to everybody,
When I use pg_bulkload with -P, -u and -l flags, permissions for files generated are set to 600 ( -rw- --- --- ). How could I modify that behavior in order to set 644 for generated files automatically. I can't  use sudo to execute a chmod command.

Welcome any suggest. Thanks a lot!.

**Comment by bwtakacy** [comment]
I have not tried yet, but I think the PostgreSQL configuration `log_file_mode` can solve.

https://www.postgresql.org/docs/9.6/static/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-WHERE
