### ISSUE TITLE
pg_bulkload will support pg10 int the future?

### ISSUE THREAD

**Issue by LoveTommy** [ossc-db/pg_bulkload#58]
Is there any develop plan?

**Comment by amitlan** [comment]
Hello.

Are you asking if the next release of pg_bulkload will support loading into (native) partitioned tables in PG 10?

If so, I would say yes, but not in the upcoming pg_bulkload release.  The upcoming release will support PG 10 in general, but will result in error if try to load into the new native partitioned tables.  For example, if you create a partitioned table using the new feature of PG 10 as follows:

```
create table p (a int) partition by list (a);
create table p1 partition of p for values in (1);
create table p2 partition of p for values in (2);
create table p3 partition of p for values in (3);
```

Then trying to use pg_bulkload to load into `p` will fail as follows:

```
$ pg_bulkload -O p -i /tmp/nums.csv 
NOTICE: BULK LOAD START
ERROR: query failed: ERROR:  cannot load to partitioned table "p"
DETAIL: query was: SELECT * FROM pg_bulkload($1)
```

Support for partitioned tables will be added in some later release.

**Comment by LoveTommy** [comment]
ok，i know. if the version 3.2 will be support pg10 ingeneral?

**Comment by amitlan** [comment]
I meant 3.1.14 when I said the upcoming release, not 3.2.  So, 3.1.14 will support PG 10.

Work on 3.2 has not progressed much in terms of any new pg_bulkload features, so there is no immediate plan to release 3.2, only maintenance releases, that is 3.1.* releases.

**Comment by LoveTommy** [comment]
ok, thank you! I am pg kernel developer from china, and my company uses the pg_bulkload. I wish i can make a little contribution to pg_bulkload in the future.

**Comment by amitlan** [comment]
Oh, great!

If you have any plans of contributing new features to pg_bulkload (if your company allows it with appropriate legal terms), then the 3.2dev branch would be a good place for that code.

Thanks again.

**Comment by alexanderlazutkin** [comment]
v. 3.1.21 has the same issue. But I will find workaround :)

ERROR: query failed: ERROR:  unexpected reader termination
DETAIL:  ERROR:  cannot load to partitioned table "orders"
DETAIL: query was: SELECT * FROM pgbulkload.pg_bulkload($1)
