### ISSUE TITLE
Error:  shmget(id=1949974951) failed: Invalid argument

### ISSUE THREAD

**Issue by xcoderzach** [ossc-db/pg_bulkload#6]
I'm getting this error when I try to run pg_bulkloader, 

```
ERROR: query failed: ERROR:  shmget(id=1949974951) failed: Invalid argument
DETAIL: query was: SELECT * FROM pg_bulkload($1)
```

And when I try to run the tests (make installcheck), I see the same error in regressions.diff.  I'm using postgres 9.4.3.

**Comment by bwtakacy** [comment]
It seems to be a problem not about pg_bulkload,  but about kernel resources configurations of PostgreSQL server, especially shared memory.
Are there any messages in PostgreSQL server log related this?

**Comment by xcoderzach** [comment]
There weren't any errors in the postgres logs other than what I posted above, however setting a higher `shmmax` and `shmall` fixed the issue.

**Comment by bwtakacy** [comment]
Thanks for reporting.

I'm happy to hear that you solved this issue:)

**Comment by dudleycarr** [comment]
I'm having a similar issue with Postgresql 9.5 on Mac OS X. I've already increased `shmmax` considerably. I also attempted to changed `dynamic_shared_memory` to `sysv`.

**Comment by dudleycarr** [comment]
Nevermind :) Turns out my `sshmax` values were too small as well. These settings proved to be useful: http://big-elephants.com/2012-12/tuning-postgres-on-macos/
