### ISSUE TITLE
Release to PGXN?

### ISSUE THREAD

**Issue by theory** [ossc-db/pg_bulkload#62]
Looks like the last version released to [PGXN](https://pgxn.org/dist/pg_bulkload) was 3.1.9. Any chance of an update?

**Comment by MoonInsung** [comment]
Thank you for your interest in pg_bulkload!

I just released a new version(3.1.14) to PGXN.

Please check the link.
https://pgxn.org/dist/pg_bulkload

Regards.
Moon.
