### ISSUE TITLE
Some data could not be inserted by bulkload but could be inserted by another tool

### ISSUE THREAD

**Issue by GargantuarZuo** [ossc-db/pg_bulkload#65]
Some data, which could not be inserted by pg_bulkload, could be inserted by another tool called pg_loader.
For instance, I use sql.txt to build up a table ,and insert it with the data in  instance.txt. 
However,  it failed by using pg_bulkloader, and succeeded by using pg_loader,

The cmd I use with pg_loader is below: 
pgloader --type csv  --field length,city,interface_type,xdr_id,rat,imsi,imei,msisdn,machine_ip_address_type,sgw_ggsn_ip_address,enb_sgsn_ip_address,sgw_ggsn_port,enb_sgsn_port,enb_sgsn_gtp_teid,sgw_ggsn_gtp_teid,tac,cell_id,apn,app_type_code,procedure_start_time,procedure_end_time,protocol_type,app_type,app_sub_type,app_content,app_status,user_ipv4,user_ipv6,user_port,l4_protocal,app_server_ip_ipv4,app_server_ip_ipv6,app_server_port,ul_data,dl_data,ul_ip_packets,dl_ip_packets,ul_disorder_ip_packets,dl_disorder_ip_packets,ul_retrans_ip_packets,dl_retrans_ip_packets,tcp_response_time,tcp_ack_time,ul_ip_frag_packets,dl_ip_frag_packets,first_req_time,first_response_time,window_sec,mss,tcp_syn_num,tcp_status,session_end,http_version,message_type,message_status,first_http_response_time,last_content_packet_time,last_ack_time,host,uri,x_online_host,user_agent,http_content_type,refer_uri,cookie,content_length,target_behaviour,wtp_abort_type,wtp_abort_reason,title,key_word,service_behavior_flag,service_comp_flag,service_time,ie,portal,reserve1,reserve2,reserve3,reserve4 --with workers=16 --with concurrency=4 --with "fields terminated by '|'" --with "fields not enclosed" /software/bulkloader10test/instance.txt postgresql://postgres:postgres@:5432/posteva?tablename=raw_s1u_http_test 

[sql.txt](https://github.com/ossc-db/pg_bulkload/files/1512759/sql.txt)

[instance.txt](https://github.com/ossc-db/pg_bulkload/files/1512755/instance.txt)

**Comment by yamatattsu** [comment]
Hi GargantuarZuo,

I tested pg_bulkload using your sql.txt and instance.txt on PG10.3.  It was successful.
Please see below. 

## $ psql -f sql.txt
psql:sql.txt:21: NOTICE:  table "raw_s1u_http" does not exist, skipping
DROP TABLE
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX

## $ cat sample.ctl
OUTPUT = public.raw_s1u_http                  # [<schema_name>.]table_name
INPUT = instance.txt  # Input data location (absolute path)
TYPE = CSV                            # Input file type
QUOTE = "\""                          # Quoting character
ESCAPE = \                            # Escape character for Quoting
DELIMITER = "|"                       # Delimiter
WRITER = BUFFERED

## $ pg_bulkload sample.ctl
NOTICE: BULK LOAD START
NOTICE: BULK LOAD END
        0 Rows skipped.
        5 Rows successfully loaded.
        0 Rows not loaded due to parse errors.
        0 Rows not loaded due to duplicate errors.
        0 Rows replaced with new rows.

## $ psql -c "select count(*) from public.raw_s1u_http;"

`` count``
``-------``
``         5``

Thanks,
Tatsuro Yamada

**Comment by yamatattsu** [comment]
closed.
