### ISSUE TITLE
Cannot build in Docker Container against Postgres 10.1

### ISSUE THREAD

**Issue by Jagjit-Thind** [ossc-db/pg_bulkload#66]
Hi, I cannot build in a docker container against postgres 10.1, I receive the error below. It seems some packages are missing, but I have installed everything stated in [installation](http://ossc-db.github.io/pg_bulkload/pg_bulkload.html#install)

My docker file is [Dockerfile.postgres.txt](https://github.com/ossc-db/pg_bulkload/files/1545285/Dockerfile.postgres.txt)

Thank you for your help

Step 4/4 : RUN **cd pg_bulkload && make**
 ---> Running in c898b35fc114
make[1]: Entering directory '/pg_bulkload/bin'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fdebug-prefix-map=/build/postgresql-10-YdsZNw/postgresql-10-10.1=. -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pg_bulkload.o pg_bulkload.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fdebug-prefix-map=/build/postgresql-10-YdsZNw/postgresql-10-10.1=. -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o recovery.o recovery.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fdebug-prefix-map=/build/postgresql-10-YdsZNw/postgresql-10-10.1=. -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pgut/pgut.o pgut/pgut.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fdebug-prefix-map=/build/postgresql-10-YdsZNw/postgresql-10-10.1=. -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pgut/pgut-fe.o pgut/pgut-fe.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fdebug-prefix-map=/build/postgresql-10-YdsZNw/postgresql-10-10.1=. -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pgut/pgut-list.o pgut/pgut-list.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fdebug-prefix-map=/build/postgresql-10-YdsZNw/postgresql-10-10.1=. -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer pg_bulkload.o recovery.o pgut/pgut.o pgut/pgut-fe.o pgut/pgut-list.o -L/usr/lib/x86_64-linux-gnu -lpq -L/usr/lib/x86_64-linux-gnu -Wl,-z,relro -Wl,-z,now  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed -Wl,--build-id  -lpgcommon -lpgport -lpthread -lselinux -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm -o pg_bulkload
**/usr/bin/ld: cannot find -lselinux
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto**
collect2: error: ld returned 1 exit status
make[1]: *** [pg_bulkload] Error 1
/usr/lib/postgresql/10/lib/pgxs/src/makefiles/pgxs.mk:300: recipe for target 'pg_bulkload' failed
make[1]: Leaving directory '/pg_bulkload/bin'
Makefile:27: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by atorik** [comment]
Thanks for reporting and sorry for late replay.

I've reproduced the err and it can be solved by adding to install libssl-dev and libselinux-dev.
I think we should add these packages to the installation manual.
