### ISSUE TITLE
How to load part of the column from csv file to a table

### ISSUE THREAD

**Issue by Mad-Apes** [ossc-db/pg_bulkload#67]
Hello,

I have two problems and I hope to get your help.

### 1 How to load part of the column from csv file to a table?
A cvs file contains following column:

value_a|value_b|value_c|value_d|value_e|value_f

The table only contains three of them:

column_a,
column_b,
column_c

so,what should I do to load `value_a` to `column_a`, `value_b` to`column_b`, `value_c` to `column_c`?

Is there any functions which can provide arguments to let us load columns which we wanted to table?
### 2 Load indntity type value.

When load indntity type value, when the value is NULL, can it automatically be assigned a non-NULL value? How to do?

best regards, thank you.

**Comment by atorik** [comment]
I think FILTER functions will help you in both cases.
FILTER  functions enable you to transfrom the input format.
About FILTER function, see [the manual](http://ossc-db.github.io/pg_bulkload/pg_bulkload.html#details).
