### ISSUE TITLE
3.1.14 build error against PostgreSQL 11

### ISSUE THREAD

**Issue by devrimgunduz** [ossc-db/pg_bulkload#70]
Hi,

Latest version cannot be compiled against PostgreSQL 11. Beta 3 is already out. Can you please take a look?

`usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o source.o source.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I../include -I/usr/pgsql-11/include -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o writer.o writer.c
pg_btree.c:40:2: error: #error unsupported PostgreSQL version
 #error unsupported PostgreSQL version
  ^~~~~
In file included from pg_btree.c:65:
../include/pg_btree.h:21:2: error: unknown type name 'BTSpool'
  BTSpool    **spools;  /**< index spool */
  ^~~~~~~
pg_btree.c:83:8: error: unknown type name 'BTSpool'
 static BTSpool **IndexSpoolBegin(ResultRelInfo *relinfo, bool enforceUnique);
        ^~~~~~~
pg_btree.c:85:30: error: unknown type name 'BTSpool'
 static void IndexSpoolInsert(BTSpool **spools, TupleTableSlot *slot, ItemPointer tupleid, EState *estate);
                              ^~~~~~~
pg_btree.c:87:38: error: unknown type name 'BTSpool'
 static IndexTuple BTSpoolGetNextItem(BTSpool *spool, IndexTuple itup, bool *should_free);
                                      ^~~~~~~
pg_btree.c:93:43: error: unknown type name 'BTSpool'
 static void _bt_mergebuild(Spooler *self, BTSpool *btspool);
                                           ^~~~~~~
pg_btree.c:94:42: error: unknown type name 'BTWriteState'; did you mean 'LimitState'?
 static void _bt_mergeload(Spooler *self, BTWriteState *wstate, BTSpool *btspool,
                                          ^~~~~~~~~~~~
                                          LimitState
pg_btree.c:94:64: error: unknown type name 'BTSpool'
 static void _bt_mergeload(Spooler *self, BTWriteState *wstate, BTSpool *btspool,
                                                                ^~~~~~~
pg_btree.c: In function 'SpoolerInsert':
pg_btree.c:171:2: warning: implicit declaration of function 'IndexSpoolInsert'; did you mean 'IndexSpoolEnd'? [-Wimplicit-function-declaration]
  IndexSpoolInsert(self->spools, self->slot, &(tuple->t_self), self->estate);
  ^~~~~~~~~~~~~~~~
  IndexSpoolEnd
pg_btree.c: At top level:
pg_btree.c:178:8: error: unknown type name 'BTSpool'
 static BTSpool **
        ^~~~~~~
pg_btree.c: In function 'IndexSpoolBegin':
pg_btree.c:184:2: error: unknown type name 'BTSpool'
  BTSpool    **spools;
  ^~~~~~~
parser_csv.c: In function 'CSVParserInit':
parser_csv.c:236:44: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
     if (strcmp(lfirst(name), desc->attrs[i]->attname.data) == 0)
                                            ^~
In file included from /usr/pgsql-11/include/server/postgres.h:47,
                 from ../include/pg_bulkload.h:9,
                 from parser_csv.c:11:
parser_csv.c: In function 'CSVParserRead':
parser_csv.c:694:91: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
            NameStr(self->former.desc->attrs[self->former.attnum[self->base.parsing_field]]->attname)),
                                                                                           ^~
/usr/pgsql-11/include/server/utils/elog.h:107:14: note: in definition of macro 'ereport_domain'
    errfinish rest; \
              ^~~~
parser_csv.c:692:4: note: in expansion of macro 'ereport'
    ereport(ERROR, (errcode(ERRCODE_INTERNAL_ERROR),
    ^~~~~~~
parser_csv.c:694:12: note: in expansion of macro 'NameStr'
            NameStr(self->former.desc->attrs[self->former.attnum[self->base.parsing_field]]->attname)),
            ^~~~~~~
make[2]: *** [<builtin>: parser_csv.o] Error 1
make[2]: *** Waiting for unfinished jobs....
pg_btree.c:189:38: error: 'BTSpool' undeclared (first use in this function)
  spools = palloc(numIndices * sizeof(BTSpool *));
                                      ^~~~~~~
pg_btree.c:189:38: note: each undeclared identifier is reported only once for each function it appears in
pg_btree.c:189:47: error: expected expression before ')' token
  spools = palloc(numIndices * sizeof(BTSpool *));
                                               ^
pg_btree.c:200:16: warning: implicit declaration of function '_bt_spoolinit'; did you mean '_bt_pageinit'? [-Wimplicit-function-declaration]
    spools[i] = _bt_spoolinit(heapRel,indices[i],
                ^~~~~~~~~~~~~
                _bt_pageinit
pg_btree.c:200:14: warning: assignment to 'int *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
    spools[i] = _bt_spoolinit(heapRel,indices[i],
              ^
pg_btree.c:209:13: error: request for member 'isunique' in something not a structure or union
    spools[i]->isunique = indices[i]->rd_index->indisunique;
             ^~
pg_btree.c: In function 'IndexSpoolEnd':
pg_btree.c:224:2: error: unknown type name 'BTSpool'
  BTSpool **spools = self->spools;
  ^~~~~~~
pg_btree.c:238:4: warning: implicit declaration of function '_bt_mergebuild'; did you mean 'btbuild'? [-Wimplicit-function-declaration]
    _bt_mergebuild(self, spools[i]);
    ^~~~~~~~~~~~~~
    btbuild
parser_function.c: In function 'FunctionParserInit':
parser_function.c:297:23: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   self->desc->attrs[i]->attnotnull = desc->attrs[i]->attnotnull;
                       ^~
parser_function.c:297:52: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   self->desc->attrs[i]->attnotnull = desc->attrs[i]->attnotnull;
                                                    ^~
make[2]: *** [<builtin>: parser_function.o] Error 1
pg_btree.c:239:4: warning: implicit declaration of function '_bt_spooldestroy'; did you mean 'hash_destroy'? [-Wimplicit-function-declaration]
    _bt_spooldestroy(spools[i]);
    ^~~~~~~~~~~~~~~~
    hash_destroy
pg_btree.c: At top level:
pg_btree.c:270:18: error: unknown type name 'BTSpool'
 IndexSpoolInsert(BTSpool **spools, TupleTableSlot *slot, ItemPointer tupleid, EState *estate)
                  ^~~~~~~
pg_btree.c:367:31: error: unknown type name 'BTSpool'
 _bt_mergebuild(Spooler *self, BTSpool *btspool)
                               ^~~~~~~
pg_btree.c:450:30: error: unknown type name 'BTWriteState'; did you mean 'LimitState'?
 _bt_mergeload(Spooler *self, BTWriteState *wstate, BTSpool *btspool, BTReader *btspool2, Relation heapRel)
                              ^~~~~~~~~~~~
                              LimitState
pg_btree.c:450:52: error: unknown type name 'BTSpool'
 _bt_mergeload(Spooler *self, BTWriteState *wstate, BTSpool *btspool, BTReader *btspool2, Relation heapRel)
                                                    ^~~~~~~
pg_btree.c:648:20: error: unknown type name 'BTSpool'
 BTSpoolGetNextItem(BTSpool *spool, IndexTuple itup, bool *should_free)
                    ^~~~~~~
pg_btree.c: In function 'tuple_to_cstring':
pg_btree.c:1035:24: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   if (tupdesc->attrs[i]->attisdropped)
                        ^~
pg_btree.c:1052:39: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
    getTypeOutputInfo(tupdesc->attrs[i]->atttypid,
                                       ^~
At top level:
pg_btree.c:952:1: warning: 'remove_duplicate' defined but not used [-Wunused-function]
 remove_duplicate(Spooler *self, Relation heap, IndexTuple itup, const char *relname)
 ^~~~~~~~~~~~~~~~
pg_btree.c:938:1: warning: 'heap_is_visible' defined but not used [-Wunused-function]
 heap_is_visible(Relation heapRel, ItemPointer htid)
 ^~~~~~~~~~~~~~~
pg_btree.c:872:1: warning: 'compare_indextuple' defined but not used [-Wunused-function]
 compare_indextuple(const IndexTuple itup1, const IndexTuple itup2,
 ^~~~~~~~~~~~~~~~~~
pg_btree.c:820:1: warning: 'BTReaderGetNextItem' defined but not used [-Wunused-function]
 BTReaderGetNextItem(BTReader *reader)
 ^~~~~~~~~~~~~~~~~~~
pg_btree.c:783:1: warning: 'BTReaderTerm' defined but not used [-Wunused-function]
 BTReaderTerm(BTReader *reader)
 ^~~~~~~~~~~~
pg_btree.c:680:1: warning: 'BTReaderInit' defined but not used [-Wunused-function]
 BTReaderInit(BTReader *reader, Relation rel)
 ^~~~~~~~~~~~
make[2]: *** [<builtin>: pg_btree.o] Error 1
pg_strutil.c: In function 'ParseFunction':
pg_strutil.c:645:29: error: 'ACL_KIND_NAMESPACE' undeclared (first use in this function); did you mean 'LOGIN_NAME_MAX'?
   aclcheck_error(aclresult, ACL_KIND_NAMESPACE,
                             ^~~~~~~~~~~~~~~~~~
                             LOGIN_NAME_MAX
pg_strutil.c:645:29: note: each undeclared identifier is reported only once for each function it appears in
pg_strutil.c:650:29: error: 'ACL_KIND_PROC' undeclared (first use in this function); did you mean 'ACL_ID_PUBLIC'?
   aclcheck_error(aclresult, ACL_KIND_PROC,
                             ^~~~~~~~~~~~~
                             ACL_ID_PUBLIC
make[2]: *** [<builtin>: pg_strutil.o] Error 1
In file included from pg_bulkload.c:35:
../include/pg_btree.h:21:2: error: unknown type name 'BTSpool'
  BTSpool    **spools;  /**< index spool */
  ^~~~~~~
pg_bulkload.c: In function 'VerifyTarget':
pg_bulkload.c:413:36: error: 'ACL_KIND_CLASS' undeclared (first use in this function); did you mean 'OCLASS_CLASS'?
   aclcheck_error(ACLCHECK_NO_PRIV, ACL_KIND_CLASS,
                                    ^~~~~~~~~~~~~~
                                    OCLASS_CLASS
pg_bulkload.c:413:36: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [<builtin>: pg_bulkload.o] Error 1
reader.c: In function 'CheckerInit':
reader.c:461:27: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
    checker->desc->attrs[i]->attnotnull = desc->attrs[i]->attnotnull;
                           ^~
reader.c:461:56: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
    checker->desc->attrs[i]->attnotnull = desc->attrs[i]->attnotnull;
                                                        ^~
reader.c: In function 'CheckerConstraints':
reader.c:555:22: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
    if (desc->attrs[i]->attnotnull &&
                      ^~
In file included from /usr/pgsql-11/include/server/postgres.h:47,
                 from ../include/pg_bulkload.h:9,
                 from reader.c:11:
reader.c:562:29: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
       NameStr(desc->attrs[i]->attname))));
                             ^~
/usr/pgsql-11/include/server/utils/elog.h:107:14: note: in definition of macro 'ereport_domain'
    errfinish rest; \
              ^~~~
reader.c:559:5: note: in expansion of macro 'ereport'
     ereport(ERROR,
     ^~~~~~~
reader.c:562:7: note: in expansion of macro 'NameStr'
       NameStr(desc->attrs[i]->attname))));
       ^~~~~~~
reader.c: In function 'TupleFormerInit':
reader.c:580:25: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   former->desc->attrs[i]->attnotnull = desc->attrs[i]->attnotnull;
                         ^~
reader.c:580:54: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   former->desc->attrs[i]->attnotnull = desc->attrs[i]->attnotnull;
                                                      ^~
reader.c:627:9: warning: assignment to 'FormData_pg_attribute **' {aka 'struct FormData_pg_attribute **'} from incompatible pointer type 'FormData_pg_attribute *' {aka 'struct FormData_pg_attribute *'} [-Wincompatible-pointer-types]
   attrs = desc->attrs;
         ^
reader.c: In function 'tupledesc_match':
reader.c:733:29: error: incompatible types when initializing type 'Form_pg_attribute' {aka 'struct FormData_pg_attribute *'} using type 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'}
   Form_pg_attribute dattr = dst_tupdesc->attrs[i];
                             ^~~~~~~~~~~
reader.c:734:29: error: incompatible types when initializing type 'Form_pg_attribute' {aka 'struct FormData_pg_attribute *'} using type 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'}
   Form_pg_attribute sattr = src_tupdesc->attrs[i];
                             ^~~~~~~~~~~
reader.c: In function 'CreateTupleChecker':
reader.c:1062:34: error: macro "AllocSetContextCreate" passed 5 arguments, but takes just 3
          ALLOCSET_DEFAULT_MAXSIZE);
                                  ^
reader.c:1058:12: error: 'AllocSetContextCreate' undeclared (first use in this function); did you mean 'SlabContextCreate'?
  context = AllocSetContextCreate(CurrentMemoryContext,
            ^~~~~~~~~~~~~~~~~~~~~
            SlabContextCreate
reader.c:1058:12: note: each undeclared identifier is reported only once for each function it appears in
reader.c: In function 'CoercionDeformTuple':
reader.c:1141:34: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
    if (self->sourceDesc->attrs[i]->atttypid ==
                                  ^~
reader.c:1142:31: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
     self->targetDesc->attrs[i]->atttypid)
                               ^~
reader.c:1145:48: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
    getTypeOutputInfo(self->sourceDesc->attrs[i]->atttypid,
                                                ^~
reader.c:1149:47: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
    getTypeInputInfo(self->targetDesc->attrs[i]->atttypid, &iofunc,
                                               ^~
reader.c:1164:33: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   if (self->targetDesc->attrs[i]->attisdropped)
                                 ^~
reader.c:1172:38: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
   else if (self->sourceDesc->attrs[i]->atttypid ==
                                      ^~
reader.c:1173:32: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
      self->targetDesc->attrs[i]->atttypid)
                                ^~
reader.c:1184:37: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
           self->targetDesc->attrs[i]->atttypmod);
                                     ^~
make[2]: *** [<builtin>: reader.o] Error 1
source.c: In function 'CreateAsyncSource':
source.c:165:32: error: macro "AllocSetContextCreate" passed 5 arguments, but takes just 3
        ALLOCSET_DEFAULT_MAXSIZE);
                                ^
source.c:160:18: error: 'AllocSetContextCreate' undeclared (first use in this function); did you mean 'SlabContextCreate'?
  self->context = AllocSetContextCreate(
                  ^~~~~~~~~~~~~~~~~~~~~
                  SlabContextCreate
source.c:160:18: note: each undeclared identifier is reported only once for each function it appears in
source.c: In function 'CreateRemoteSource':
source.c:480:22: error: invalid type argument of '->' (have 'FormData_pg_attribute' {aka 'struct FormData_pg_attribute'})
    if (desc->attrs[i]->attisdropped)
                      ^~
make[2]: *** [<builtin>: source.o] Error 1
`

**Comment by devrimgunduz** [comment]
I mean, I saw fixes in git -- can you please roll out a new release?

**Comment by theory** [comment]
I too would love to see a new release with the fixes for Postgres 11. Want to start pulling from PGXN, too!

**Comment by theory** [comment]
Looking forward to it!

**Comment by theory** [comment]
I got a 3.1.15 announcement email this morning, but now it's not [there](/ossc-db/pg_bulkload/releases/)…
