### ISSUE TITLE
how do I load csv format data with no QUOTE or ESCAPE

### ISSUE THREAD

**Issue by qianxiansheng90** [ossc-db/pg_bulkload#71]
ctl file:
INPUT = /data1/dumpdata.csv
PARSE_BADFILE = /home/postgres/tbl_lottu_bad.txt
LOGFILE = /home/postgres/tbl_lottu_output.log
LIMIT = INFINITE
PARSE_ERRORS = 0
CHECK_CONSTRAINTS = NO
TYPE = CSV
QUOTE=
ESCAPE=
OUTPUT = test.test
MULTI_PROCESS = NO
WRITER = DIRECT
DUPLICATE_BADFILE = /home/postgres/tbl_lottu.dup.csv
DUPLICATE_ERRORS = 0
ON_DUPLICATE_KEEP = NEW
TRUNCATE = YES

file in /data1/dumpdata.csv like this:
5589557359      1023    402
delimiter is tab,with no QUOTE and no ESCAPE

run with pg_bulkload with error:
pg_bulkload pg_buldload.ctl --host=localhost --port=5432 --user=postgres  --dbname=text  -o $'DELIMITER=\t'
get error:
ERROR: invalid input "QUOTE"

how can i resolve this;

**Comment by MoonInsung** [comment]
Dear @qianfangyuan 
The CSV file you provided, it seems that there are no strings for QUOTE and ESCAPE.
So, remove the QUOTE and ESCAPE in the CTL file to make it work by default.
Maybe it will probably work usually.
For more information, plz see this manual
http://ossc-db.github.io/pg_bulkload/pg_bulkload.html
