### ISSUE TITLE
OSX minor build issue - ld: unknown option: --build-id

### ISSUE THREAD

**Issue by poorlymac** [ossc-db/pg_bulkload#74]
When building on OSX Mojave 10.14.2 with Xcode 10.1 I get the error ld: unknown option: --build-id as it seems the --build-id flag isn't supported by the ld that ships with OSX. I was able to build fine by commenting out the LDFLAGS+=-Wl,--build-id in bin/Makefile and lib/Makefile, I am not sure of a more correct solution to a clean build myself.

**Comment by MoonInsung** [comment]
Dear @poorlymac 

I’m afraid, but the pg_bulkload does not support the macOS.
Please check the #101 contents for more details.

Best regards.
Moon.
