### ISSUE TITLE
Build error against PostgreSQL 12

### ISSUE THREAD

**Issue by devrimgunduz** [ossc-db/pg_bulkload#77]
Hi,

PostgreSQL 12 is near, and I'm reporting extension bugs. pg_bulkload cannot be compiled against PostgreSQL 12:

`gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I../include -I/usr/pgsql-12/include -I. -I./ -I/usr/pgsql-12/include/server -I/usr/pgsql-12/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o writer_binary.o writer_binary.c
pg_btree.c:27:10: fatal error: utils/tqual.h: No such file or directory
   27 | #include "utils/tqual.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [<builtin>: pg_btree.o] Error 1
make[2]: *** Waiting for unfinished jobs....
parser_function.c:41:2: error: unknown type name 'FunctionCallInfoData'
   41 |  FunctionCallInfoData fcinfo;
      |  ^~~~~~~~~~~~~~~~~~~~
parser_function.c: In function 'FunctionParserInit':
parser_function.c:153:16: error: request for member 'argnull' in something not a structure or union
  153 |    self->fcinfo.argnull[i] = true;
      |                ^
parser_function.c:161:16: error: request for member 'arg' in something not a structure or union
  161 |    self->fcinfo.arg[i] = OidInputFunctionCall(typinput,
      |                ^
parser_function.c:163:16: error: request for member 'argnull' in something not a structure or union
  163 |    self->fcinfo.argnull[i] = false;
      |                ^
parser_function.c:216:15: error: request for member 'arg' in something not a structure or union
  216 |   self->fcinfo.arg[nfixedarg] = PointerGetDatum(arry);
      |               ^
parser_function.c:265:16: error: request for member 'arg' in something not a structure or union
  265 |    self->fcinfo.arg[nargs] = ExecEvalExpr(argstate,
      |                ^
parser_function.c:267:29: error: request for member 'argnull' in something not a structure or union
  267 |                &self->fcinfo.argnull[nargs]
      |                             ^
In file included from /usr/pgsql-12/include/server/access/skey.h:19,
                 from /usr/pgsql-12/include/server/access/heapam.h:20,
                 from parser_function.c:13:
/usr/pgsql-12/include/server/fmgr.h:152:11: error: request for member 'flinfo' in something not a structure or union
  152 |   (Fcinfo).flinfo = (Flinfo); \
      |           ^
parser_function.c:288:2: note: in expansion of macro 'InitFunctionCallInfoData'
  288 |  InitFunctionCallInfoData(self->fcinfo, &self->flinfo, nargs,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-12/include/server/fmgr.h:153:11: error: request for member 'context' in something not a structure or union
  153 |   (Fcinfo).context = (Context); \
      |           ^
parser_function.c:288:2: note: in expansion of macro 'InitFunctionCallInfoData'
  288 |  InitFunctionCallInfoData(self->fcinfo, &self->flinfo, nargs,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-12/include/server/fmgr.h:154:11: error: request for member 'resultinfo' in something not a structure or union
  154 |   (Fcinfo).resultinfo = (Resultinfo); \
      |           ^
parser_function.c:288:2: note: in expansion of macro 'InitFunctionCallInfoData'
  288 |  InitFunctionCallInfoData(self->fcinfo, &self->flinfo, nargs,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-12/include/server/fmgr.h:155:11: error: request for member 'fncollation' in something not a structure or union
  155 |   (Fcinfo).fncollation = (Collation); \
      |           ^
parser_function.c:288:2: note: in expansion of macro 'InitFunctionCallInfoData'
  288 |  InitFunctionCallInfoData(self->fcinfo, &self->flinfo, nargs,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-12/include/server/fmgr.h:156:11: error: request for member 'isnull' in something not a structure or union
  156 |   (Fcinfo).isnull = false; \
      |           ^
parser_function.c:288:2: note: in expansion of macro 'InitFunctionCallInfoData'
  288 |  InitFunctionCallInfoData(self->fcinfo, &self->flinfo, nargs,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-12/include/server/fmgr.h:157:11: error: request for member 'nargs' in something not a structure or union
  157 |   (Fcinfo).nargs = (Nargs); \
      |           ^
parser_function.c:288:2: note: in expansion of macro 'InitFunctionCallInfoData'
  288 |  InitFunctionCallInfoData(self->fcinfo, &self->flinfo, nargs,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
parser_function.c:313:25: error: too few arguments to function 'MakeSingleTupleTableSlot'
  313 |  self->funcResultSlot = MakeSingleTupleTableSlot(self->desc);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-12/include/server/tcop/dest.h:70,
                 from /usr/pgsql-12/include/server/utils/guc.h:17,
                 from /usr/pgsql-12/include/server/access/tableam.h:22,
                 from /usr/pgsql-12/include/server/access/heapam.h:22,
                 from parser_function.c:13:
/usr/pgsql-12/include/server/executor/tuptable.h:302:24: note: declared here
  302 | extern TupleTableSlot *MakeSingleTupleTableSlot(TupleDesc tupdesc,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~
parser_function.c: In function 'FunctionParserRead':
parser_function.c:373:11: warning: implicit declaration of function 'ExecFetchSlotTupleDatum'; did you mean 'ExecFetchSlotHeapTupleDatum'? [-Wimplicit-function-declaration]
  373 |   datum = ExecFetchSlotTupleDatum(self->funcResultSlot);
      |           ^~~~~~~~~~~~~~~~~~~~~~~
      |           ExecFetchSlotHeapTupleDatum
parser_function.c:381:29: warning: passing argument 1 of 'pgstat_init_function_usage' from incompatible pointer type [-Wincompatible-pointer-types]
  381 |  pgstat_init_function_usage(&self->fcinfo, &fcusage);
      |                             ^~~~~~~~~~~~~
      |                             |
      |                             int *
In file included from parser_function.c:20:
/usr/pgsql-12/include/server/pgstat.h:1405:57: note: expected 'FunctionCallInfo' {aka 'struct FunctionCallInfoBaseData *'} but argument is of type 'int *'
 1405 | extern void pgstat_init_function_usage(FunctionCallInfo fcinfo,
      |                                        ~~~~~~~~~~~~~~~~~^~~~~~
parser_function.c:383:14: error: request for member 'isnull' in something not a structure or union
  383 |  self->fcinfo.isnull = false;
      |              ^
In file included from /usr/pgsql-12/include/server/access/skey.h:19,
                 from /usr/pgsql-12/include/server/access/heapam.h:20,
                 from parser_function.c:13:
/usr/pgsql-12/include/server/fmgr.h:167:48: error: request for member 'flinfo' in something not a structure or union
  167 | #define FunctionCallInvoke(fcinfo) ((* (fcinfo)->flinfo->fn_addr) (fcinfo))
      |                                                ^~
parser_function.c:385:10: note: in expansion of macro 'FunctionCallInvoke'
  385 |  datum = FunctionCallInvoke(&self->fcinfo);
      |          ^~~~~~~~~~~~~~~~~~
parser_function.c:404:19: error: request for member 'isnull' in something not a structure or union
  404 |   if (self->fcinfo.isnull)
      |                   ^
make[2]: *** [<builtin>: parser_function.o] Error 1
reader.c: In function 'CheckerInit':
reader.c:452:19: error: too few arguments to function 'MakeSingleTupleTableSlot'
  452 |   checker->slot = MakeSingleTupleTableSlot(desc);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-12/include/server/tcop/dest.h:70,
                 from /usr/pgsql-12/include/server/utils/guc.h:17,
                 from /usr/pgsql-12/include/server/access/tableam.h:22,
                 from /usr/pgsql-12/include/server/access/heapam.h:22,
                 from reader.c:16:
/usr/pgsql-12/include/server/executor/tuptable.h:302:24: note: declared here
  302 | extern TupleTableSlot *MakeSingleTupleTableSlot(TupleDesc tupdesc,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~
reader.c: In function 'CheckerConstraints':
reader.c:544:3: warning: implicit declaration of function 'ExecStoreTuple'; did you mean 'ExecStoreHeapTuple'? [-Wimplicit-function-declaration]
  544 |   ExecStoreTuple(tuple, checker->slot, InvalidBuffer, false);
      |   ^~~~~~~~~~~~~~
      |   ExecStoreHeapTuple
reader.c: In function 'tupledesc_match':
reader.c:758:17: error: 'struct TupleDescData' has no member named 'tdhasoid'
  758 |  if (dst_tupdesc->tdhasoid != src_tupdesc->tdhasoid)
      |                 ^~
reader.c:758:42: error: 'struct TupleDescData' has no member named 'tdhasoid'
  758 |  if (dst_tupdesc->tdhasoid != src_tupdesc->tdhasoid)
      |                                          ^~
In file included from /usr/pgsql-12/include/server/postgres.h:47,
                 from ../include/pg_bulkload.h:9,
                 from reader.c:11:
reader.c:763:21: error: 'struct TupleDescData' has no member named 'tdhasoid'
  763 |          src_tupdesc->tdhasoid, dst_tupdesc->tdhasoid)));
      |                     ^~
/usr/pgsql-12/include/server/utils/elog.h:125:14: note: in definition of macro 'ereport_domain'
  125 |    errfinish rest; \
      |              ^~~~
reader.c:759:3: note: in expansion of macro 'ereport'
  759 |   ereport(ERROR,
      |   ^~~~~~~
reader.c:763:44: error: 'struct TupleDescData' has no member named 'tdhasoid'
  763 |          src_tupdesc->tdhasoid, dst_tupdesc->tdhasoid)));
      |                                            ^~
/usr/pgsql-12/include/server/utils/elog.h:125:14: note: in definition of macro 'ereport_domain'
  125 |    errfinish rest; \
      |              ^~~~
reader.c:759:3: note: in expansion of macro 'ereport'
  759 |   ereport(ERROR,
      |   ^~~~~~~
reader.c: In function 'FilterTuple':
reader.c:975:2: error: unknown type name 'FunctionCallInfoData'; did you mean 'FunctionCallInfoBaseData'?
  975 |  FunctionCallInfoData fcinfo;
      |  ^~~~~~~~~~~~~~~~~~~~
      |  FunctionCallInfoBaseData
In file included from /usr/pgsql-12/include/server/access/skey.h:19,
                 from /usr/pgsql-12/include/server/access/heapam.h:20,
                 from reader.c:16:
/usr/pgsql-12/include/server/fmgr.h:152:11: error: request for member 'flinfo' in something not a structure or union
  152 |   (Fcinfo).flinfo = (Flinfo); \
      |           ^
reader.c:1024:2: note: in expansion of macro 'InitFunctionCallInfoData'
 1024 |  InitFunctionCallInfoData(fcinfo, &flinfo, filter->nargs, filter->collation, NULL, NULL);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-12/include/server/fmgr.h:153:11: error: request for member 'context' in something not a structure or union
  153 |   (Fcinfo).context = (Context); \
      |           ^
reader.c:1024:2: note: in expansion of macro 'InitFunctionCallInfoData'
 1024 |  InitFunctionCallInfoData(fcinfo, &flinfo, filter->nargs, filter->collation, NULL, NULL);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-12/include/server/fmgr.h:154:11: error: request for member 'resultinfo' in something not a structure or union
  154 |   (Fcinfo).resultinfo = (Resultinfo); \
      |           ^
reader.c:1024:2: note: in expansion of macro 'InitFunctionCallInfoData'
 1024 |  InitFunctionCallInfoData(fcinfo, &flinfo, filter->nargs, filter->collation, NULL, NULL);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-12/include/server/fmgr.h:155:11: error: request for member 'fncollation' in something not a structure or union
  155 |   (Fcinfo).fncollation = (Collation); \
      |           ^
reader.c:1024:2: note: in expansion of macro 'InitFunctionCallInfoData'
 1024 |  InitFunctionCallInfoData(fcinfo, &flinfo, filter->nargs, filter->collation, NULL, NULL);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-12/include/server/fmgr.h:156:11: error: request for member 'isnull' in something not a structure or union
  156 |   (Fcinfo).isnull = false; \
      |           ^
reader.c:1024:2: note: in expansion of macro 'InitFunctionCallInfoData'
 1024 |  InitFunctionCallInfoData(fcinfo, &flinfo, filter->nargs, filter->collation, NULL, NULL);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-12/include/server/fmgr.h:157:11: error: request for member 'nargs' in something not a structure or union
  157 |   (Fcinfo).nargs = (Nargs); \
      |           ^
reader.c:1024:2: note: in expansion of macro 'InitFunctionCallInfoData'
 1024 |  InitFunctionCallInfoData(fcinfo, &flinfo, filter->nargs, filter->collation, NULL, NULL);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
reader.c:1031:9: error: request for member 'arg' in something not a structure or union
 1031 |   fcinfo.arg[i] = former->values[i];
      |         ^
reader.c:1032:9: error: request for member 'argnull' in something not a structure or union
 1032 |   fcinfo.argnull[i] = former->isnull[i];
      |         ^
reader.c:1051:29: warning: passing argument 1 of 'pgstat_init_function_usage' from incompatible pointer type [-Wincompatible-pointer-types]
 1051 |  pgstat_init_function_usage(&fcinfo, &fcusage);
      |                             ^~~~~~~
      |                             |
      |                             int *
In file included from reader.c:24:
/usr/pgsql-12/include/server/pgstat.h:1405:57: note: expected 'FunctionCallInfo' {aka 'struct FunctionCallInfoBaseData *'} but argument is of type 'int *'
 1405 | extern void pgstat_init_function_usage(FunctionCallInfo fcinfo,
      |                                        ~~~~~~~~~~~~~~~~~^~~~~~
reader.c:1053:8: error: request for member 'isnull' in something not a structure or union
 1053 |  fcinfo.isnull = false;
      |        ^
In file included from /usr/pgsql-12/include/server/access/skey.h:19,
                 from /usr/pgsql-12/include/server/access/heapam.h:20,
                 from reader.c:16:
/usr/pgsql-12/include/server/fmgr.h:167:48: error: request for member 'flinfo' in something not a structure or union
  167 | #define FunctionCallInvoke(fcinfo) ((* (fcinfo)->flinfo->fn_addr) (fcinfo))
      |                                                ^~
reader.c:1057:11: note: in expansion of macro 'FunctionCallInvoke'
 1057 |   datum = FunctionCallInvoke(&fcinfo);
      |           ^~~~~~~~~~~~~~~~~~
reader.c:1084:12: error: request for member 'isnull' in something not a structure or union
 1084 |  if (fcinfo.isnull)
      |            ^
make[2]: *** [<builtin>: reader.o] Error 1
writer_binary.c: In function 'BinaryWriterInit':
writer_binary.c:113:12: error: too many arguments to function 'CreateTemplateTupleDesc'
  113 |  tupdesc = CreateTemplateTupleDesc(self->nfield, false);
      |            ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ../include/pg_bulkload.h:18,
                 from writer_binary.c:7:
/usr/pgsql-12/include/server/access/tupdesc.h:94:18: note: declared here
   94 | extern TupleDesc CreateTemplateTupleDesc(int natts);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [<builtin>: writer_binary.o] Error 1
make[2]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/pg_bulkload/master/pg_bulkload-VERSION3_1_15/lib'
make[1]: *** [Makefile:27: all] Error 2
make[1]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/pg_bulkload/master/pg_bulkload-VERSION3_1_15'
error: Bad exit status from /var/tmp/rpm-tmp.E57cBj (%build)
`

Can you please take a look?

Thanks, Devrim

**Comment by devrimgunduz** [comment]
ping.

**Comment by MoonInsung** [comment]
Thank you for reporting.
I will soon release pgbulkload to respond to pg12 after any maintenance.

**Comment by devrimgunduz** [comment]
ping again :)

**Comment by theory** [comment]
Looking forward to an update on PGXN, too. Thanks!

**Comment by devrimgunduz** [comment]
ping.

**Comment by theory** [comment]
ping. 🛎

**Comment by theory** [comment]
Fixed in v3.1.16?

**Comment by devrimgunduz** [comment]
Yeah.
