### ISSUE TITLE
pg_bulkload installation issues on Docker 

### ISSUE THREAD

**Issue by priyasooraj** [ossc-db/pg_bulkload#89]
Hi,
I am trying to install pg_bulkload on Docker and while doing so I am seeing the following errors - 
```
root@c3094244af63:/# cd pg_bulkload-3.1.4
                root@c3094244af63:/pg_bulkload-3.1.4# make
                Makefile:33: warning: overriding recipe for target 'check'
                /usr/lib/postgresql/12/lib/pgxs/src/makefiles/pgxs.mk:433: warning: ignoring old recipe for target 'check'
                make[1]: Entering directory '/pg_bulkload-3.1.4/bin'
                gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o recovery.o recovery.c
                recovery.c: In function ‘IsPageCreatedByLoader’:
                recovery.c:556:7: warning: implicit declaration of function ‘PageHeaderIsValid’; did you mean ‘PageSizeIsValid’? [-Wimplicit-function-declaration]
                if (!PageHeaderIsValid(targetBlock))
                    ^~~~~~~~~~~~~~~~~
                    PageSizeIsValid
                recovery.c: At top level:
                recovery.c:909:1: warning: no previous prototype for ‘PageHeaderIsValid’ [-Wmissing-prototypes]
                PageHeaderIsValid(PageHeader page)
                ^~~~~~~~~~~~~~~~~
                recovery.c:909:1: error: conflicting types for ‘PageHeaderIsValid’
                recovery.c:556:7: note: previous implicit declaration of ‘PageHeaderIsValid’ was here
                if (!PageHeaderIsValid(targetBlock))
                    ^~~~~~~~~~~~~~~~~
                make[1]: *** [<builtin>: recovery.o] Error 1
                make[1]: Leaving directory '/pg_bulkload-3.1.4/bin'
                make: *** [Makefile:27: all] Error 2

                Kindly check and let me know what we must be doing to get past this error.
```

**Comment by priyasooraj** [comment]
Please note the version I have installed in 3.1.14 and the pg version I am using is V12

**Comment by priyasooraj** [comment]
tried to install 3.1.16 and getting a new error :
root@e16a3fb11846:/pg_bulkload-3.1.16# make
Makefile:33: warning: overriding recipe for target 'check'
/usr/lib/postgresql/12/lib/pgxs/src/makefiles/pgxs.mk:433: warning: ignoring old recipe for target 'check'
make[1]: Entering directory '/pg_bulkload-3.1.16/bin'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pg_bulkload.o pg_bulkload.c
In file included from pgut/pgut-fe.h:13,
                 from pg_bulkload.c:17:
pgut/pgut.h:13:10: fatal error: c.h: No such file or directory
 #include "c.h"
          ^~~~~
compilation terminated.
make[1]: *** [<builtin>: pg_bulkload.o] Error 1

**Comment by Anonyma** [comment]
^ getting the same error on v3.1.17

**Comment by Anonyma** [comment]
If you're using PostgreSQL <13, you need to use the code in this branch: [REL_UNDER_PG13_STABLE](https://github.com/ossc-db/pg_bulkload/tree/REL_UNDER_PG13_STABLE)

I got it working with that.
