### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by walpino** [ossc-db/pg_bulkload#9]
Hello
we are trying to replace oracle (sqlldr )

is it possible that the csv has 4 columns an I can import them in a table with only 3 columns? the last column would be ignored

we just upgraded to 9.5 as well so we a 9.5 package would be great

**Comment by bwtakacy** [comment]
Hello,

There is STRIDE option which handles the length of input record, but this option can be used if all the input records have the same length.

If not, it is possible to do so by using `cut` command together (not a smart way...).
For example,
```
$ cut -d',' -f1,2 input.csv | pg_bulkoad load.ctl
```
where the input.csv has the three columns and the pg_bulkload uses 'INPUT=stdin' at load.ctl.
