### ISSUE TITLE
Release v3.1.17 on PGXN

### ISSUE THREAD

**Issue by theory** [ossc-db/pg_bulkload#90]
Looks like the current [latest on PGXN is still 3.1.16](https://pgxn.org/dist/pg_bulkload).

**Comment by theory** [comment]
Also 3.1.18.

**Comment by yanmeisun** [comment]
Thanks for reminding and sorry for the late reply.
We have released v3.1.18 on PGXN today. As for v3.1.17, since it was separated into 2 branches according to different PostgreSQL version, we think it is difficult to release it on PGXN. As a result, we didn't release it on PGXN.
