### ISSUE TITLE
utils/elog.h: No such file or directory

### ISSUE THREAD

**Issue by meow23571379** [ossc-db/pg_bulkload#99]
Hi, 

I was installing pg_bulkload and when I executed `make` or `make USE_PGXS=1` in the top directory of pg_bulkload, there was an error message as below.  I have searched about this file but couldn't find one in this repo.  Did I do anything wrong? 
`user@mac ~/pg_bulkload (master)> make` 
```
Makefile:33: warning: overriding recipe for target 'check'
/usr/lib/postgresql/13/lib/pgxs/src/makefiles/pgxs.mk:433: warning: ignoring old recipe for target 'check'
make[1]: Entering directory '/home/user/pg_bulkload/bin'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -I../include -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pg_bulkload.o pg_bulkload.c
In file included from pgut/pgut-fe.h:13,
                 from pg_bulkload.c:17:
pgut/pgut.h:25:10: fatal error: utils/elog.h: No such file or directory
   25 | #include "utils/elog.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: pg_bulkload.o] Error 1
make[1]: Leaving directory '/home/user/pg_bulkload/bin'
make: *** [Makefile:27: all] Error 2
```

Best, 
Bonnie

**Comment by mikecaat** [comment]
Hi,

> I have searched about this file but couldn't find one in this repo. 
It seems that you need to install the postgresql first because the file is not a pg_bulkload's one, but postgresql's library.

But, in the first place, I recommend building it on Linux environments like RHEL/CentOS.
This project has not developed for mac, so it may be other problems to build it.

**Comment by mikecaat** [comment]
I tested whether we can build it or not on mac os. 
Although we need to fix some codes, this [PR](https://github.com/ossc-db/pg_bulkload/pull/101) can build it and [the result is ok](https://github.com/ossc-db/pg_bulkload/runs/2543033515?check_suite_focus=true).

- versions

```
ProductName:	Mac OS X
ProductVersion: 10.15.7
BuildVersion:	19H1030
```

- building procedure

```
brew update
brew install postgresql@13
cd pg_bulkload  # master branch
make
```

**Comment by mikecaat** [comment]
The [PR](https://github.com/ossc-db/pg_bulkload/pull/101) will be rejected. You can see the reason on the PR page. 
So, you need to build it on RHEL/CentOS. Sorry.

Regards,
Masahiro Ikeda
